const mongoose = require("mongoose");
require("dotenv").config();

const MONGODB_URI =
  process.env.MONGODB_URI || "mongodb://localhost:27017/library_management";

const bookData = [
  // Fantasy Books (10)
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    isbn: "9780547928227",
    genre: ["Fantasy", "Adventure"],
    publicationYear: 1937,
    publisher: "George Allen & Unwin",
    copiesAvailable: 4,
    totalCopies: 5,
    description: "A fantasy novel about the adventures of Bilbo Baggins",
    language: "English",
    pages: 310,
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    isbn: "9780590353427",
    genre: ["Fantasy", "Young Adult"],
    publicationYear: 1997,
    publisher: "Bloomsbury",
    copiesAvailable: 3,
    totalCopies: 5,
    description: "The first book in the Harry Potter series",
    language: "English",
    pages: 223,
  },
  {
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    isbn: "9780756404741",
    genre: ["Fantasy", "Epic Fantasy"],
    publicationYear: 2007,
    publisher: "DAW Books",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "The story of Kvothe, a legendary magician and musician",
    language: "English",
    pages: 662,
  },
  {
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    isbn: "9780553103540",
    genre: ["Fantasy", "Political", "Epic Fantasy"],
    publicationYear: 1996,
    publisher: "Bantam Spectra",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "The first novel in A Song of Ice and Fire series",
    language: "English",
    pages: 694,
  },
  {
    title: "The Way of Kings",
    author: "Brandon Sanderson",
    isbn: "9780765326355",
    genre: ["Fantasy", "Epic Fantasy"],
    publicationYear: 2010,
    publisher: "Tor Books",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "First book in The Stormlight Archive series",
    language: "English",
    pages: 1007,
  },
  {
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    isbn: "9780066238500",
    genre: ["Fantasy", "Children's", "Adventure"],
    publicationYear: 1950,
    publisher: "Geoffrey Bles",
    copiesAvailable: 4,
    totalCopies: 5,
    description: "A series of seven fantasy novels",
    language: "English",
    pages: 767,
  },
  {
    title: "The Wheel of Time",
    author: "Robert Jordan",
    isbn: "9780312850098",
    genre: ["Fantasy", "Epic Fantasy"],
    publicationYear: 1990,
    publisher: "Tor Books",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "First book in The Wheel of Time series",
    language: "English",
    pages: 814,
  },
  {
    title: "Mistborn: The Final Empire",
    author: "Brandon Sanderson",
    isbn: "9780765311788",
    genre: ["Fantasy", "Epic Fantasy"],
    publicationYear: 2006,
    publisher: "Tor Books",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "First book in the Mistborn series",
    language: "English",
    pages: 541,
  },
  {
    title: "The Lies of Locke Lamora",
    author: "Scott Lynch",
    isbn: "9780553588941",
    genre: ["Fantasy", "Heist", "Adventure"],
    publicationYear: 2006,
    publisher: "Gollancz",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "First book in the Gentleman Bastard series",
    language: "English",
    pages: 499,
  },
  {
    title: "The Priory of the Orange Tree",
    author: "Samantha Shannon",
    isbn: "9781635570298",
    genre: ["Fantasy", "Epic Fantasy", "Dragons"],
    publicationYear: 2019,
    publisher: "Bloomsbury",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "A standalone epic fantasy novel",
    language: "English",
    pages: 848,
  },

  // Science Fiction Books (10)
  {
    title: "Dune",
    author: "Frank Herbert",
    isbn: "9780441172719",
    genre: ["Science Fiction", "Epic"],
    publicationYear: 1965,
    publisher: "Chilton Books",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "Epic science fiction novel set in the distant future",
    language: "English",
    pages: 412,
  },
  {
    title: "1984",
    author: "George Orwell",
    isbn: "9780451524935",
    genre: ["Science Fiction", "Dystopian", "Political"],
    publicationYear: 1949,
    publisher: "Secker & Warburg",
    copiesAvailable: 4,
    totalCopies: 5,
    description: "A dystopian social science fiction novel",
    language: "English",
    pages: 328,
  },
  {
    title: "Foundation",
    author: "Isaac Asimov",
    isbn: "9780553293357",
    genre: ["Science Fiction", "Space Opera"],
    publicationYear: 1951,
    publisher: "Gnome Press",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "First book in the Foundation series",
    language: "English",
    pages: 255,
  },
  {
    title: "Neuromancer",
    author: "William Gibson",
    isbn: "9780441569595",
    genre: ["Science Fiction", "Cyberpunk"],
    publicationYear: 1984,
    publisher: "Ace Books",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "The novel that defined the cyberpunk genre",
    language: "English",
    pages: 271,
  },
  {
    title: "Ender's Game",
    author: "Orson Scott Card",
    isbn: "9780812550702",
    genre: ["Science Fiction", "Military", "Young Adult"],
    publicationYear: 1985,
    publisher: "Tor Books",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "Military science fiction novel",
    language: "English",
    pages: 324,
  },
  {
    title: "The Left Hand of Darkness",
    author: "Ursula K. Le Guin",
    isbn: "9780441478125",
    genre: ["Science Fiction", "Anthropological"],
    publicationYear: 1969,
    publisher: "Ace Books",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "Science fiction novel exploring gender and society",
    language: "English",
    pages: 304,
  },
  {
    title: "Snow Crash",
    author: "Neal Stephenson",
    isbn: "9780553380958",
    genre: ["Science Fiction", "Cyberpunk", "Satire"],
    publicationYear: 1992,
    publisher: "Bantam Spectra",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "Cyberpunk novel with elements of satire",
    language: "English",
    pages: 470,
  },
  {
    title: "The Martian",
    author: "Andy Weir",
    isbn: "9780553418026",
    genre: ["Science Fiction", "Hard Science Fiction", "Survival"],
    publicationYear: 2011,
    publisher: "Crown Publishing",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "A man is stranded on Mars and must survive",
    language: "English",
    pages: 369,
  },
  {
    title: "Children of Time",
    author: "Adrian Tchaikovsky",
    isbn: "9781447273288",
    genre: ["Science Fiction", "Space Opera", "Evolution"],
    publicationYear: 2015,
    publisher: "Tor Books",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "Epic science fiction about evolution and society",
    language: "English",
    pages: 600,
  },
  {
    title: "Project Hail Mary",
    author: "Andy Weir",
    isbn: "9780593135204",
    genre: ["Science Fiction", "Space", "First Contact"],
    publicationYear: 2021,
    publisher: "Ballantine Books",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "A lone astronaut must save humanity",
    language: "English",
    pages: 476,
  },

  // Thriller Books (10)
  {
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    isbn: "9780307269751",
    genre: ["Thriller", "Mystery", "Crime"],
    publicationYear: 2005,
    publisher: "Norstedts Förlag",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "A journalist and a hacker investigate a disappearance",
    language: "English",
    pages: 465,
  },
  {
    title: "Gone Girl",
    author: "Gillian Flynn",
    isbn: "9780307588364",
    genre: ["Thriller", "Mystery", "Psychological"],
    publicationYear: 2012,
    publisher: "Crown Publishing",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "A psychological thriller about a marriage gone wrong",
    language: "English",
    pages: 415,
  },
  {
    title: "The Da Vinci Code",
    author: "Dan Brown",
    isbn: "9780307474278",
    genre: ["Thriller", "Mystery", "Conspiracy"],
    publicationYear: 2003,
    publisher: "Doubleday",
    copiesAvailable: 4,
    totalCopies: 5,
    description: "A murder mystery involving secret societies",
    language: "English",
    pages: 454,
  },
  {
    title: "The Silent Patient",
    author: "Alex Michaelides",
    isbn: "9781250301697",
    genre: ["Thriller", "Psychological", "Mystery"],
    publicationYear: 2019,
    publisher: "Celadon Books",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "A psychological thriller about a woman who stops speaking",
    language: "English",
    pages: 336,
  },
  {
    title: "The Reversal",
    author: "Michael Connelly",
    isbn: "9780316069489",
    genre: ["Thriller", "Legal", "Crime"],
    publicationYear: 2010,
    publisher: "Little, Brown",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "A legal thriller about a retrial",
    language: "English",
    pages: 400,
  },
  {
    title: "Sharp Objects",
    author: "Gillian Flynn",
    isbn: "9780307341556",
    genre: ["Thriller", "Psychological", "Crime"],
    publicationYear: 2006,
    publisher: "Shaye Archeart Books",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "A reporter returns to her hometown to cover a murder",
    language: "English",
    pages: 254,
  },
  {
    title: "The Woman in the Window",
    author: "A.J. Finn",
    isbn: "9780062678416",
    genre: ["Thriller", "Psychological", "Mystery"],
    publicationYear: 2018,
    publisher: "William Morrow",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "An agoraphobic woman witnesses a crime",
    language: "English",
    pages: 427,
  },
  {
    title: "The Chain",
    author: "Adrian McKinty",
    isbn: "9780316531269",
    genre: ["Thriller", "Suspense", "Kidnapping"],
    publicationYear: 2019,
    publisher: "Little, Brown",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "A mother must kidnap another child to save her own",
    language: "English",
    pages: 352,
  },
  {
    title: "The Night Fire",
    author: "Michael Connelly",
    isbn: "9780316485616",
    genre: ["Thriller", "Police Procedural", "Crime"],
    publicationYear: 2019,
    publisher: "Little, Brown",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "Harry Bosch investigates an old murder case",
    language: "English",
    pages: 400,
  },
  {
    title: "One by One",
    author: "Ruth Ware",
    isbn: "9781501188817",
    genre: ["Thriller", "Mystery", "Suspense"],
    publicationYear: 2020,
    publisher: "Gallery/Scout Press",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "A corporate retreat turns deadly",
    language: "English",
    pages: 372,
  },

  // Horror Books (5)
  {
    title: "The Shining",
    author: "Stephen King",
    isbn: "9780385121675",
    genre: ["Horror", "Psychological", "Supernatural"],
    publicationYear: 1977,
    publisher: "Doubleday",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "A family confronts supernatural forces at a hotel",
    language: "English",
    pages: 447,
  },
  {
    title: "It",
    author: "Stephen King",
    isbn: "9780670813025",
    genre: ["Horror", "Supernatural", "Coming-of-Age"],
    publicationYear: 1986,
    publisher: "Viking Press",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "Seven children are terrorized by an evil entity",
    language: "English",
    pages: 1138,
  },
  {
    title: "Dracula",
    author: "Bram Stoker",
    isbn: "9780194794000",
    genre: ["Horror", "Gothic", "Classic"],
    publicationYear: 1897,
    publisher: "Archibald Constable and Company",
    copiesAvailable: 4,
    totalCopies: 5,
    description: "The classic vampire novel",
    language: "English",
    pages: 418,
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    isbn: "9780486282114",
    genre: ["Horror", "Gothic", "Science Fiction"],
    publicationYear: 1818,
    publisher: "Lackington, Hughes",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "A scientist creates a sentient creature",
    language: "English",
    pages: 280,
  },
  {
    title: "The Haunting of Hill House",
    author: "Shirley Jackson",
    isbn: "9780143039983",
    genre: ["Horror", "Psychological", "Gothic"],
    publicationYear: 1959,
    publisher: "Viking Press",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "Four people stay in a haunted mansion",
    language: "English",
    pages: 246,
  },

  // Romance Books (5)
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "9780141439518",
    genre: ["Romance", "Classic", "Historical"],
    publicationYear: 1813,
    publisher: "T. Egerton",
    copiesAvailable: 4,
    totalCopies: 5,
    description: "A romantic novel of manners",
    language: "English",
    pages: 432,
  },
  {
    title: "The Notebook",
    author: "Nicholas Sparks",
    isbn: "9780446605236",
    genre: ["Romance", "Contemporary", "Drama"],
    publicationYear: 1996,
    publisher: "Warner Books",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "A love story that spans decades",
    language: "English",
    pages: 214,
  },
  {
    title: "Outlander",
    author: "Diana Gabaldon",
    isbn: "9780440212560",
    genre: ["Romance", "Historical", "Fantasy"],
    publicationYear: 1991,
    publisher: "Delacorte Press",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "A time-travel romance set in Scotland",
    language: "English",
    pages: 850,
  },
  {
    title: "The Hating Game",
    author: "Sally Thorne",
    isbn: "9780062439598",
    genre: ["Romance", "Contemporary", "Romantic Comedy"],
    publicationYear: 2016,
    publisher: "William Morrow",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "Two workplace rivals fall in love",
    language: "English",
    pages: 384,
  },
  {
    title: "Red, White & Royal Blue",
    author: "Casey McQuiston",
    isbn: "9781250316776",
    genre: ["Romance", "LGBTQ+", "Contemporary"],
    publicationYear: 2019,
    publisher: "St. Martin's Griffin",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "A romance between the First Son and a Prince",
    language: "English",
    pages: 423,
  },

  // Classic Books (5)
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "9780061120084",
    genre: ["Classic", "Historical", "Southern Gothic"],
    publicationYear: 1960,
    publisher: "J.B. Lippincott & Co.",
    copiesAvailable: 4,
    totalCopies: 5,
    description: "A novel about racial inequality and moral growth",
    language: "English",
    pages: 281,
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "9780743273565",
    genre: ["Classic", "Tragedy", "American"],
    publicationYear: 1925,
    publisher: "Scribner",
    copiesAvailable: 3,
    totalCopies: 4,
    description: "A story of the Jazz Age and the American Dream",
    language: "English",
    pages: 180,
  },
  {
    title: "Moby-Dick",
    author: "Herman Melville",
    isbn: "9780142437247",
    genre: ["Classic", "Adventure", "American"],
    publicationYear: 1851,
    publisher: "Harper & Brothers",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "The epic tale of Captain Ahab's quest for revenge",
    language: "English",
    pages: 635,
  },
  {
    title: "War and Peace",
    author: "Leo Tolstoy",
    isbn: "9780199232765",
    genre: ["Classic", "Historical", "Epic"],
    publicationYear: 1869,
    publisher: "The Russian Messenger",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "A novel that chronicles the French invasion of Russia",
    language: "English",
    pages: 1225,
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    isbn: "9780143058144",
    genre: ["Classic", "Psychological", "Philosophical"],
    publicationYear: 1866,
    publisher: "The Russian Messenger",
    copiesAvailable: 2,
    totalCopies: 3,
    description: "A psychological exploration of guilt and redemption",
    language: "English",
    pages: 671,
  },
];

async function generateBooks() {
  try {
    console.log("🔗 Connecting to MongoDB...");
    await mongoose.connect(MONGODB_URI);
    console.log("✅ Connected to MongoDB");

    // Define the Book schema
    const BookSchema = new mongoose.Schema(
      {
        title: String,
        author: String,
        isbn: String,
        genre: [String],
        publicationYear: Number,
        publisher: String,
        copiesAvailable: Number,
        totalCopies: Number,
        description: String,
        language: String,
        pages: Number,
      },
      { timestamps: true }
    );

    const Book = mongoose.model("Book", BookSchema);

    // Clear existing books
    console.log("🗑️  Clearing existing books...");
    await Book.deleteMany({});
    console.log("✅ Existing books cleared");

    // Insert new books
    console.log("📚 Generating 50 books...");
    const createdBooks = await Book.insertMany(bookData);
    console.log(`✅ Created ${createdBooks.length} books`);

    // Show summary by genre
    const genreSummary = {};
    bookData.forEach((book) => {
      book.genre.forEach((g) => {
        genreSummary[g] = (genreSummary[g] || 0) + 1;
      });
    });

    console.log("\n📊 Genre Distribution:");
    console.log("=====================");
    Object.entries(genreSummary).forEach(([genre, count]) => {
      console.log(`${genre}: ${count} books`);
    });

    console.log("\n🎉 Book generation complete!");
  } catch (error) {
    console.error("❌ Error generating books:", error);
  } finally {
    await mongoose.disconnect();
    console.log("🔌 Disconnected from MongoDB");
    process.exit(0);
  }
}

generateBooks();
